### ISSUE TITLE
Amazon Linux 2023 install fails with: mondoo package for cnquery and cnspec installation failed (can't find the cnspec binary).

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/installer#433] opened 2024-02-14 16:10 UTC
**Describe the bug**
Just tried to install cnquery and cnspec on Amazon Linux 2023 from the Integrations Marketplace:

![image](https://github.com/mondoohq/installer/assets/49754039/f466778a-4157-44cc-9fe0-5b7e95ad2294)

Installation failed with `mondoo package for cnquery and cnspec installation failed (can't find the cnspec binary).`

![image](https://github.com/mondoohq/installer/assets/49754039/1052cb1b-8231-4105-b429-9ed664b8352a)

**Comment by czunker** [comment] 2024-06-06 08:47
Cannot reproduce this. I assume it was fixed in the meantime.

I created an EC2 instance, connect via ssh, installed mondoo:
```
export MONDOO_REGISTRATION_TOKEN='xxx'
curl -sSL https://install.mondoo.com/sh | bash -s -- -u enable -s enable -t $MONDOO_REGISTRATION_TOKEN
```

All as expected:
```
[ec2-user@ip-172-31-24-187 ~]$ cnspec version
! can't find any paths for providers, none are configured home-path=/home/ec2-user/.config/mondoo/providers system-path=/opt/mondoo/providers
cnspec 11.7.3 (3ee2786, 2024-06-05T17:14:34Z)
[ec2-user@ip-172-31-24-187 ~]$ cnspec status
! can't find any paths for providers, none are configured home-path=/home/ec2-user/.config/mondoo/providers system-path=/opt/mondoo/providers
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ Platform:		amazonlinux
→ Version:		2023
→ Hostname:		ip-172-31-24-187.eu-central-1.compute.internal
→ IP:			172.31.24.187
→ Time:			2024-06-06T08:45:34Z
→ Version:		11.7.3 (API Version: 11)
→ Latest Version:	11.7.3
→ Installed Providers:	core | mock | sbom
→ API ConnectionConfig:	https://api.edge.mondoo.com
→ API Status:		SERVING
→ API Time:		2024-06-06T08:45:34Z
→ API Version:		11
→ Owner:		//captain.api.mondoo.app/spaces/elastic-payne-456551
→ Client:		//agents.api.mondoo.app/spaces/elastic-payne-456551/agents/2hUzbsRqwNC17NbSDVxH9eofPgO
→ Service Account:		//agents.api.mondoo.app/spaces/elastic-payne-456551/serviceaccounts/2hUzbyqx67vchi1PYUcQu0bm0NW
→ client is registered
→ client authenticated successfully
[ec2-user@ip-172-31-24-187 ~]$ cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023.4.20240528"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/amazon-linux-2023/"
DOCUMENTATION_URL="https://docs.aws.amazon.com/linux/"
SUPPORT_URL="https://aws.amazon.com/premiumsupport/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
VENDOR_NAME="AWS"
VENDOR_URL="https://aws.amazon.com/"
SUPPORT_END="2028-03-15"
[ec2-user@ip-172-31-24-187 ~]$ 

```

**Closed by czunker** 2024-06-06 08:47 UTC
